FROM golang:1.24-alpine AS builder


WORKDIR /app

# Копируем файлы зависимостей и скачиваем их
COPY ./go.mod ./go.sum ./
RUN go mod download

# Копируем исходный код
COPY . .

# Собираем приложение
RUN CGO_ENABLED=0 GOOS=linux go build cmd/web/main.go

# Финальный образ
FROM alpine:latest

WORKDIR /app

# Копируем собранный бинарник
COPY --from=builder /app/main .
COPY --from=builder /app/templates ./templates
COPY --from=builder /app/config ./config

EXPOSE 8080

CMD ["./main"]